#### Que2.-
In this dataset you have to predict that whether we have to give ATTORNEY to the clients or not (0=Yes, 1=No) based on below factors.
CLMAGE - Age of Client
CLMSEX - Sex of client (0=Male, 1= Female)
SEATBELT - Whether client has Seatbelt or not (0=Yes, 1=No)
CLMINSUR - Whether Client give Insurance or not (0=Yes, 1=No)
LOSS - Loss that client faced

Prepare model by using logistic regression,Naive Bayes,KNN and SVM & Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score, roc auc score, precision, recall.

Dataset : Claimants.csv


In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
df = pd.read_csv('claimants.csv')
df


ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ATTORNEY  1340 non-null   int64  
 1   CLMSEX    1328 non-null   float64
 2   CLMINSUR  1299 non-null   float64
 3   SEATBELT  1292 non-null   float64
 4   CLMAGE    1151 non-null   float64
 5   LOSS      1340 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 62.9 KB


In [57]:
df.describe()

ATTORNEY       CLMSEX     CLMINSUR     SEATBELT       CLMAGE  \
count  1340.000000  1328.000000  1299.000000  1292.000000  1151.000000   
mean      0.488806     0.558735     0.907621     0.017028    28.414422   
std       0.500061     0.496725     0.289671     0.129425    20.304451   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     1.000000     0.000000     9.000000   
50%       0.000000     1.000000     1.000000     0.000000    30.000000   
75%       1.000000     1.000000     1.000000     0.000000    43.000000   
max       1.000000     1.000000     1.000000     1.000000    95.000000   

              LOSS  
count  1340.000000  
mean      3.806307  
std      10.636903  
min       0.000000  
25%       0.400000  
50%       1.069500  
75%       3.781500  
max     173.604000

In [58]:
df.corr()

ATTORNEY    CLMSEX  CLMINSUR  SEATBELT    CLMAGE      LOSS
ATTORNEY  1.000000  0.079674  0.079439 -0.057189  0.010680 -0.219715
CLMSEX    0.079674  1.000000  0.066413 -0.015024 -0.023195 -0.027611
CLMINSUR  0.079439  0.066413  1.000000  0.021154  0.049493  0.005821
SEATBELT -0.057189 -0.015024  0.021154  1.000000 -0.027992  0.111189
CLMAGE    0.010680 -0.023195  0.049493 -0.027992  1.000000  0.064612
LOSS     -0.219715 -0.027611  0.005821  0.111189  0.064612  1.000000

In [59]:
df.isna().sum()

ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [60]:
df.mean()

ATTORNEY     0.488806
CLMSEX       0.558735
CLMINSUR     0.907621
SEATBELT     0.017028
CLMAGE      28.414422
LOSS         3.806307
dtype: float64

In [61]:
mean = df['CLMAGE'].mean()
mean

28.414422241529106

In [62]:
df['CLMAGE'].fillna(mean, inplace = True)
df

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
0            0     0.0       1.0       0.0  50.000000  34.940
1            1     1.0       0.0       0.0  18.000000   0.891
2            1     0.0       1.0       0.0   5.000000   0.330
3            0     0.0       1.0       1.0  31.000000   0.037
4            1     0.0       1.0       0.0  30.000000   0.038
...        ...     ...       ...       ...        ...     ...
1335         1     0.0       1.0       0.0  28.414422   0.576
1336         0     1.0       1.0       0.0  46.000000   3.705
1337         1     1.0       1.0       0.0  39.000000   0.099
1338         0     1.0       0.0       0.0   8.000000   3.177
1339         1     1.0       1.0       0.0  30.000000   0.688

[1340 rows x 6 columns]

In [63]:
df.isna().sum()

ATTORNEY     0
CLMSEX      12
CLMINSUR    41
SEATBELT    48
CLMAGE       0
LOSS         0
dtype: int64

In [64]:
df1 = df.dropna()

In [79]:
df1.isna().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [80]:
df1.corr()

ATTORNEY    CLMSEX  CLMINSUR  SEATBELT    CLMAGE      LOSS
ATTORNEY  1.000000  0.085329  0.084624 -0.058185  0.000749 -0.220631
CLMSEX    0.085329  1.000000  0.062882 -0.015918 -0.016567 -0.028468
CLMINSUR  0.084624  0.062882  1.000000  0.021461  0.045440  0.004760
SEATBELT -0.058185 -0.015918  0.021461  1.000000 -0.026957  0.111177
CLMAGE    0.000749 -0.016567  0.045440 -0.026957  1.000000  0.058467
LOSS     -0.220631 -0.028468  0.004760  0.111177  0.058467  1.000000

In [81]:
X = df1.drop('ATTORNEY', axis = 1)
Y = df1['ATTORNEY']


In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,train_size=0.7,random_state=12345)

### Model Building

In [83]:
def logistic_regression():
    from sklearn.linear_model import LogisticRegressionCV
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [84]:
def naive_bayes():
    from sklearn.naive_bayes import GaussianNB
    model = GaussianNB()
    model.fit(x_train, y_train)
    return model

In [85]:
def KNN():
    from sklearn.neighbors import KNeighborsClassifier
    model = KNeighborsClassifier(n_neighbors=7)
    model.fit(x_train, y_train)
    return model

In [86]:
def SVM():
    from sklearn.svm import SVC
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [87]:
# get nb model
model_nb = naive_bayes()

# get KNN model
model_knn = KNN()

# get SVM model
model_svm = SVM()

# get logistic regression model
model_logistic_regression = logistic_regression()

#### Evaluation 

In [88]:
def evaluate_model(model):
    from sklearn.metrics import confusion_matrix, accuracy_score, precision_score,recall_score, f1_score
    y_true = y_test
    y_pred = model.predict(x_test)

    cm = confusion_matrix(y_true, y_pred)
    print(cm)

    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precision = {precision_score(y_true, y_pred)*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred)*100:.2f}%")
    print(f"F1 Score = {f1_score(y_true, y_pred)*100:.2f}%")
    
    

In [89]:
# evaluate logistic nb model
evaluate_model(model_nb)

[[ 57 150]
 [ 16 158]]
accuracy = 56.43%
precision = 51.30%
recall = 90.80%
F1 Score = 65.56%


In [90]:
# evaluate knn model
evaluate_model(model_knn)

[[119  88]
 [ 39 135]]
accuracy = 66.67%
precision = 60.54%
recall = 77.59%
F1 Score = 68.01%


In [91]:
# evaluate svm model
evaluate_model(model_svm)

[[107 100]
 [ 27 147]]
accuracy = 66.67%
precision = 59.51%
recall = 84.48%
F1 Score = 69.83%


In [92]:
#evaluate logistic regression
evaluate_model(model_logistic_regression)

[[122  85]
 [ 35 139]]
accuracy = 68.50%
precision = 62.05%
recall = 79.89%
F1 Score = 69.85%
