### Que3.-

The model's main purpose is to predict the 10-year risk of Coronary Heart Disease (CHD). CHD is a disease of the blood vessels supplying the heart. Heart disease has been the leading cause of death worldwide since 1921. In 2008, 7.3 million people died from CHD. 
The classification goal is to predict whether the patient has 10-year risk of future coronary heart disease (CHD).The dataset provides the patients’ information. It includes over 4,000 records and 15 attributes.
Variables
Sex: male or female(0=female, 1=male)
Age: Age of the patient
education: Some high school (1), high school/GED (2), some college/vocational school (3), college (4)
Current Smoker: whether or not the patient is a currendf = t smoker (0=No, 1=Yes)
Cigs Per Day: the number of cigarettes that the person smoked on average in one day
BP Meds: whether or not the patient was on blood pressure medication 
Prevalent Stroke: whether or not the patient had previously had a stroke (0=No, 1=Yes)
Prevalent Hyp: whether or not the patient was hypertensive (0=No, 1=Yes)
Diabetes: whether or not the patient had diabetes (0=No, 1=Yes)
Tot Chol: total cholesterol level
Sys BP: systolic blood pressure 
Dia BP: diastolic blood pressure
BMI: Body Mass Index
Heart Rate: heart rate
Glucose: glucose level

Prepare model by using logistic regression KNN and SVM.

Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score, roc auc score, precision, recall.

Datasets : framingham.csv 

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [14]:
df1 = pd.read_csv('framingham.csv')
df1.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [15]:
df1.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4240 non-null   int64  
 1   age              4240 non-null   int64  
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64  
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64  
 7   prevalentHyp     4240 non-null   int64  
 8   diabetes         4240 non-null   int64  
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 530.1 KB


In [17]:
df =  df1.dropna()

In [20]:
df.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [18]:
df.corr()

male       age  education  currentSmoker  cigsPerDay  \
male             1.000000 -0.024412   0.017729       0.206114    0.330322   
age             -0.024412  1.000000  -0.159499      -0.210771   -0.189295   
education        0.017729 -0.159499   1.000000       0.025251    0.013790   
currentSmoker    0.206114 -0.210771   0.025251       1.000000    0.773913   
cigsPerDay       0.330322 -0.189295   0.013790       0.773913    1.000000   
BPMeds          -0.052124  0.134732  -0.013739      -0.051923   -0.046504   
prevalentStroke -0.002312  0.050893  -0.030386      -0.038150   -0.036286   
prevalentHyp     0.001424  0.306239  -0.078828      -0.108078   -0.070460   
diabetes         0.013819  0.109092  -0.039627      -0.041849   -0.036961   
totChol         -0.070321  0.268252  -0.013522      -0.051034   -0.030400   
sysBP           -0.045358  0.388267  -0.124360      -0.134428   -0.094781   
diaBP            0.051872  0.208283  -0.058059      -0.115955   -0.056746   
BMI              0.073111  0.137511  -0.137555      -0.159821   -0.087395   
heartRate       -0.115285 -0.002722  -0.064214       0.050841    0.064030   
glucose          0.002940  0.118349  -0.031998      -0.053242   -0.053726   
TenYearCHD       0.091688  0.233983  -0.063279       0.019165    0.052014   

                   BPMeds  prevalentStroke  prevalentHyp  diabetes   totChol  \
male            -0.052124        -0.002312      0.001424  0.013819 -0.070321   
age              0.134732         0.050893      0.306239  0.109092  0.268252   
education       -0.013739        -0.030386     -0.078828 -0.039627 -0.013522   
currentSmoker   -0.051923        -0.038150     -0.108078 -0.041849 -0.051034   
cigsPerDay      -0.046504        -0.036286     -0.070460 -0.036961 -0.030400   
BPMeds           1.000000         0.113125      0.262910  0.049066  0.094083   
prevalentStroke  0.113125         1.000000      0.066057  0.009625  0.012736   
prevalentHyp     0.262910         0.066057      1.000000  0.080556  0.166655   
diabetes         0.049066         0.009625      0.080556  1.000000  0.048451   
totChol          0.094083         0.012736      0.166655  0.048451  1.000000   
sysBP            0.271263         0.061070      0.697675  0.102552  0.219925   
diaBP            0.199630         0.055834      0.617734  0.050686  0.174422   
BMI              0.105642         0.036496      0.302949  0.089009  0.121056   
heartRate        0.012889        -0.017019      0.146818  0.060984  0.093053   
glucose          0.054232         0.016061      0.086942  0.614820  0.049884   
TenYearCHD       0.089152         0.048366      0.181387  0.093431  0.091338   

                    sysBP     diaBP       BMI  heartRate   glucose  TenYearCHD  
male            -0.045358  0.051872  0.073111  -0.115285  0.002940    0.091688  
age              0.388267  0.208283  0.137511  -0.002722  0.118349    0.233983  
education       -0.124360 -0.058059 -0.137555  -0.064214 -0.031998   -0.063279  
currentSmoker   -0.134428 -0.115955 -0.159821   0.050841 -0.053242    0.019165  
cigsPerDay      -0.094781 -0.056746 -0.087395   0.064030 -0.053726    0.052014  
BPMeds           0.271263  0.199630  0.105642   0.012889  0.054232    0.089152  
prevalentStroke  0.061070  0.055834  0.036496  -0.017019  0.016061    0.048366  
prevalentHyp     0.697675  0.617734  0.302949   0.146818  0.086942    0.181387  
diabetes         0.102552  0.050686  0.089009   0.060984  0.614820    0.093431  
totChol          0.219925  0.174422  0.121056   0.093053  0.049884    0.091338  
sysBP            1.000000  0.786669  0.330917   0.184797  0.134651    0.222821  
diaBP            0.786669  1.000000  0.385348   0.178744  0.063540    0.150124  
BMI              0.330917  0.385348  1.000000   0.074131  0.083683    0.082055  
heartRate        0.184797  0.178744  0.074131   1.000000  0.097074    0.020514  
glucose          0.134651  0.063540  0.083683   0.097074  1.000000    0.121990  
TenYearCHD       0.222821  0.150124  0.082055   0.0205

In [22]:
X = df.drop('TenYearCHD', axis = 1)
Y = df['TenYearCHD']


In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,train_size=0.7,random_state=12345)

In [24]:
def logistic_regression():
    from sklearn.linear_model import LogisticRegressionCV
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [25]:
def KNN():
    from sklearn.neighbors import KNeighborsClassifier
    model = KNeighborsClassifier(n_neighbors=7)
    model.fit(x_train, y_train)
    return model

In [26]:
def SVM():
    from sklearn.svm import SVC
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [27]:
# get KNN model
model_knn = KNN()

# get SVM model
model_svm = SVM()

# get logistic regression model
model_logistic_regression = logistic_regression()

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [28]:
def evaluate_model(model):
    from sklearn.metrics import confusion_matrix, accuracy_score, precision_score,recall_score, f1_score
    y_true = y_test
    y_pred = model.predict(x_test)

    cm = confusion_matrix(y_true, y_pred)
    print(cm)

    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precision = {precision_score(y_true, y_pred)*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred)*100:.2f}%")
    print(f"F1 Score = {f1_score(y_true, y_pred)*100:.2f}%")
    
    

In [29]:
#evaluate logistic regression
evaluate_model(model_logistic_regression)

[[922   8]
 [153  15]]
accuracy = 85.34%
precision = 65.22%
recall = 8.93%
F1 Score = 15.71%


In [30]:
# evaluate knn model
evaluate_model(model_knn)

[[913  17]
 [153  15]]
accuracy = 84.52%
precision = 46.88%
recall = 8.93%
F1 Score = 15.00%


In [31]:
# evaluate svm model
evaluate_model(model_svm)

[[928   2]
 [166   2]]
accuracy = 84.70%
precision = 50.00%
recall = 1.19%
F1 Score = 2.33%
